### ISSUE TITLE
Wrong path in openshift uninstaller

### ISSUE THREAD

**Issue by Magublafix** [keptn/installer#71]
Hi,

The openshift uninstaller contains a wrong path and ends in the following error.
 error: the path "../manifests/tiller/tiller.yaml" does not exist

I guess there is a ../ missing

regards,
Gerald

**Comment by jetzlstorfer** [comment]
Are you using the master branch? 
In the current version in the develop branch this issue should already be adressed since we provide a common uninstaller for keptn (in the ./common folder)

**Comment by Magublafix** [comment]
Ah you are right.
Sorry didn't check the dev branch
